### ISSUE TITLE
Provide setting for cell CSS class prefix

### ISSUE THREAD

**Issue by psychemedia** [parmentelat/jupyterlab-celltagsclasses#3]
At the moment, the cell class is prefixed with the string`cell-tag-`:

https://github.com/parmentelat/jupyterlab-celltagsclasses/blob/9dce9dc8be59c3200ba6d97f4c853cf4d5e21dc6/src/index.ts#L36

It might be convenient to allow the user to specify this via a class prefix preference setting, or perhaps set an even more general pattern as a regex.

**Comment by parmentelat** [comment]
it feels there is a one-to-one relation ship between between tag and class..

for this reason I am a bit reluctant to going this way: for example I have already written a few extensions that rely on this one,
but none of them are going to work in a context where this naming scheme is altered by configuration

what exactly would be the use case for using another naming scheme ?

**Comment by psychemedia** [comment]
Part of the reason is simply the flexibilty. I'm refactoring https://github.com/innovationOUtside/jupyterlab_empinken_extension to use this extension (which is really handy:-) for the logical cell tag to cell HTML class mapping and have previously worked in a previous namespace with a different convention.

I do appreciate the benefits of hard-coding the prefix though eg in terms of consistency. (I don't see why your other extensions would fail though if the the default was to the current value?)

**Comment by parmentelat** [comment]
what I'm saying is, if I ship extension A that relies on the current scheme, and you ship extension B that needs to change the setting, then extensions A and B will be unable to run together (because the css rules that come with A will no longer trigger)

so imho it's better if you align your extension on the current hard-wired scheme
I understand it is painful, but otoh it's a finite change, as it does not impact the notebooks that rely on your extension

is that a convincing enough argument ?

**Comment by psychemedia** [comment]
I can absolutely see that argument, eg wrt building an ecosytsem of tools around this extension. I've just learned from experience that hard coding literals sometimes has side effects!

But yes, for now, I am coding my new css rules to fit with the current syntax of this extension.
